sources:
  - name: mainnet
    handler:
      graphql:
        endpoint: https://gateway-arbitrum.network.thegraph.com/api/subgraphs/id/AwyZBdna4vTAHiqBWsrQ5ErFRMi6HCgGEkQMgNBseWTL
        operationHeaders:
          Authorization: Bearer {env.API_KEY}
        schemaHeaders:
          Authorization: Bearer ${API_KEY}
  - name: arbitrum
    handler:
      graphql:
        endpoint: https://gateway-arbitrum.network.thegraph.com/api/subgraphs/id/DjUVVVSuKcCCTZSVzVXLioSd7AdqwGEyBrY4Ru5tuqzX
        operationHeaders:
          Authorization: Bearer {env.API_KEY}
        schemaHeaders:
          Authorization: Bearer ${API_KEY}

documents:
  - "./queries/**/*.graphql"

additionalTypeDefs: |
  enum CHAIN {
    ARBITRUM
    MAINNET
  }

  extend type Subgraph {
    deployedChain: CHAIN
  }

  extend type Query {
    crossSubgraphs(skip: Int = 0, first: Int, orderBy: Subgraph_orderBy, orderDirection: OrderDirection, where: Subgraph_filter, block: Block_height): [Subgraph!]!
  }

additionalResolvers:
  - ./utils/graphclient/resolvers.ts
